name: Seventeenth Workflow
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false

jobs:
  # Первая работа 
  call-workflow:
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}

  # Вторая работа 
  call-external-workflow:
    uses: Margog-hub/workflow/.github/workflows/workflow.yml@main
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}