name: Seventeenth Workflow
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false

jobs:
  # 1. Запуск файла, который лежит в ЭТОМ ЖЕ репозитории
  local-test:
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}

  # 2. Запуск файла из ДРУГОГО репозитория (внешнего)
  external-test:
    uses: Margog-hub/github_actions/.github/workflows/workflow.yml@main
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}