name: Seventeenth Workflow
on:
  workflow_dispatch:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false

jobs:
  # 1. Локальный воркфлоу 
  local-test:
    uses: ./.github/workflows/workflow.yml
    with:
      title: ${{ inputs.title }}
    secrets: inherit
      # PASSWORD: ${{ secrets.PASSWORD }} 

  # 2. Внешний воркфлоу
  external-test:
    uses: Margog-hub/github_actions/.github/workflows/workflow.yml@main
    with:
      title: ${{ inputs.title }}
    secrets:
      PASSWORD: ${{ secrets.PASSWORD }}