name: Reusable Workflow
on:
  workflow_call:
    inputs:
      title:
        description: "Custom Title"
        type: string
        default: "Testing text title"
        required: false
    secrets:
      PASSWORD:
        description: "Password Description"
        required: true
    # Передача данных обратно в вызывающий воркфлоу
    outputs:
      date:
        description: "The generated date"
        value: ${{ jobs.generate-output.outputs.date }}

jobs:
  console-log:
    runs-on: ubuntu-latest
    steps:
      - name: Print Title
        run: echo "Title is ${{ inputs.title }}"

  generate-output:
    runs-on: ubuntu-latest
    # Объявляем выходные данные на уровне джоба
    outputs:
      date: ${{ steps.date-step.outputs.date }}
    steps:
      - name: Generate Date
        id: date-step
        # Записываем текущую дату в специальный файл вывода GitHub
        run: echo "date=$(date)" >> $GITHUB_OUTPUT

  checkout:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: ls -a